# CONFIG_SH_AUDIO_DRIVER newly created

snd-soc-ymu828b-objs := sh_mc_asoc.o sh_mc_asoc_cdsp.o \
	mcdevif.o mcdevprof.o mcdriver.o mcmachdep.o mcpacking.o mcresctrl.o mcservice.o mcdebuglog.o mccdspdrv.o

obj-$(CONFIG_SND_SOC_YMU828B) += snd-soc-ymu828b.o
