/* include/sharp/shtps_dev_cfg.h
 *
 * Copyright (C) 2012 SHARP CORPORATION
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
#ifndef __SHTPS_DEV_CFG_H__
#define __SHTPS_DEV_CFG_H__

#if defined(CONFIG_SHTPS_TMA4XX_DEV)

	#undef CONFIG_SHTPS_TMA4XX_FACETOUCH_DETECT
	#undef CONFIG_SHTPS_TMA4XX_FACETOUCH_OFF_DETECT

	#if defined(CONFIG_SHTPS_TMA4XX_TMA463_002)	
//		#define CONFIG_SHTPS_TMA4XX_FACETOUCH_DETECT
//		#define CONFIG_SHTPS_TMA4XX_FACETOUCH_OFF_DETECT
	#endif

#elif defined(CONFIG_SHTPS_SY3X00_DEV)

	#undef CONFIG_SHTPS_SY3000_PANEL_SIZE_X
	#undef CONFIG_SHTPS_SY3000_PANEL_SIZE_Y
	#undef CONFIG_SHTPS_SY3000_LCD_SIZE_X
	#undef CONFIG_SHTPS_SY3000_LCD_SIZE_Y
	#undef CONFIG_SHTPS_SY3000_SINGLE_1ST_DRSTEP
	#undef CONFIG_SHTPS_SY3000_SINGLE_2ND_DRSTEP
	#undef CONFIG_SHTPS_SY3000_MULTI_1ST_DRSTEP
	#undef CONFIG_SHTPS_SY3000_MULTI_2ND_DRSTEP
	#undef CONFIG_SHTPS_SY3000_FACETOUCH_DETECT
	#undef CONFIG_SHTPS_SY3000_FACETOUCH_OFF_DETECT
	#undef CONFIG_SHTPS_SY3000_POSITION_OFFSET
	#undef CONFIG_SHTPS_SY3000_VIRTUAL_KEY
	#undef CONFIG_SHTPS_SY3000_ALWAYS_ACTIVEMODE
	#undef CONFIG_SHTPS_SY3000_AUTOREZERO_CONTROL
	#undef CONFIG_SHTPS_SY3000_FLIP_CHANGE_HANDLE

	#if defined(CONFIG_SHTPS_SY3000_TM2215_001)	
		#define CONFIG_SHTPS_SY3000_PANEL_SIZE_X		720
		#define CONFIG_SHTPS_SY3000_PANEL_SIZE_Y		1280
		#define CONFIG_SHTPS_SY3000_LCD_SIZE_X			CONFIG_SHTPS_SY3000_PANEL_SIZE_X
		#define CONFIG_SHTPS_SY3000_LCD_SIZE_Y			CONFIG_SHTPS_SY3000_PANEL_SIZE_Y
		#define CONFIG_SHTPS_SY3000_SINGLE_1ST_DRSTEP	8
		#define CONFIG_SHTPS_SY3000_SINGLE_2ND_DRSTEP	1
		#define CONFIG_SHTPS_SY3000_MULTI_1ST_DRSTEP	12
		#define CONFIG_SHTPS_SY3000_MULTI_2ND_DRSTEP	1
//		#define CONFIG_SHTPS_SY3000_FACETOUCH_DETECT
//		#define CONFIG_SHTPS_SY3000_FACETOUCH_OFF_DETECT
		#define CONFIG_SHTPS_SY3000_POSITION_OFFSET
//		#define CONFIG_SHTPS_SY3000_VIRTUAL_KEY
		#define CONFIG_SHTPS_SY3000_ALWAYS_ACTIVEMODE
//		#define CONFIG_SHTPS_SY3000_AUTOREZERO_CONTROL
//		#define CONFIG_SHTPS_SY3000_FLIP_CHANGE_HANDLE
	#endif

	#if defined(CONFIG_SHTPS_SY3000_TM2314_001)	
		#define CONFIG_SHTPS_SY3000_PANEL_SIZE_X		720
		#define CONFIG_SHTPS_SY3000_PANEL_SIZE_Y		1280
		#define CONFIG_SHTPS_SY3000_LCD_SIZE_X			CONFIG_SHTPS_SY3000_PANEL_SIZE_X
		#define CONFIG_SHTPS_SY3000_LCD_SIZE_Y			CONFIG_SHTPS_SY3000_PANEL_SIZE_Y
		#define CONFIG_SHTPS_SY3000_SINGLE_1ST_DRSTEP	8
		#define CONFIG_SHTPS_SY3000_SINGLE_2ND_DRSTEP	1
		#define CONFIG_SHTPS_SY3000_MULTI_1ST_DRSTEP	12
		#define CONFIG_SHTPS_SY3000_MULTI_2ND_DRSTEP	1
//		#define CONFIG_SHTPS_SY3000_FACETOUCH_DETECT
//		#define CONFIG_SHTPS_SY3000_FACETOUCH_OFF_DETECT
		#define CONFIG_SHTPS_SY3000_POSITION_OFFSET
//		#define CONFIG_SHTPS_SY3000_VIRTUAL_KEY
		#define CONFIG_SHTPS_SY3000_ALWAYS_ACTIVEMODE
//		#define CONFIG_SHTPS_SY3000_AUTOREZERO_CONTROL
//		#define CONFIG_SHTPS_SY3000_FLIP_CHANGE_HANDLE
	#endif

	#if defined(CONFIG_SHTPS_SY3000_TM2376_001)	
		#define CONFIG_SHTPS_SY3000_PANEL_SIZE_X		720
		#define CONFIG_SHTPS_SY3000_PANEL_SIZE_Y		1280
		#define CONFIG_SHTPS_SY3000_LCD_SIZE_X			CONFIG_SHTPS_SY3000_PANEL_SIZE_X
		#define CONFIG_SHTPS_SY3000_LCD_SIZE_Y			CONFIG_SHTPS_SY3000_PANEL_SIZE_Y
		#define CONFIG_SHTPS_SY3000_SINGLE_1ST_DRSTEP	8
		#define CONFIG_SHTPS_SY3000_SINGLE_2ND_DRSTEP	1
		#define CONFIG_SHTPS_SY3000_MULTI_1ST_DRSTEP	12
		#define CONFIG_SHTPS_SY3000_MULTI_2ND_DRSTEP	1
//		#define CONFIG_SHTPS_SY3000_FACETOUCH_DETECT
//		#define CONFIG_SHTPS_SY3000_FACETOUCH_OFF_DETECT
		#define CONFIG_SHTPS_SY3000_POSITION_OFFSET
//		#define CONFIG_SHTPS_SY3000_VIRTUAL_KEY
		#define CONFIG_SHTPS_SY3000_ALWAYS_ACTIVEMODE
//		#define CONFIG_SHTPS_SY3000_AUTOREZERO_CONTROL
//		#define CONFIG_SHTPS_SY3000_FLIP_CHANGE_HANDLE
	#endif

	#if defined(CONFIG_SHTPS_SY3000_TM2731_001)	
		#define CONFIG_SHTPS_SY3000_PANEL_SIZE_X		480
		#define CONFIG_SHTPS_SY3000_PANEL_SIZE_Y		854
		#define CONFIG_SHTPS_SY3000_LCD_SIZE_X			CONFIG_SHTPS_SY3000_PANEL_SIZE_X
		#define CONFIG_SHTPS_SY3000_LCD_SIZE_Y			CONFIG_SHTPS_SY3000_PANEL_SIZE_Y
		#define CONFIG_SHTPS_SY3000_SINGLE_1ST_DRSTEP	8
		#define CONFIG_SHTPS_SY3000_SINGLE_2ND_DRSTEP	1
		#define CONFIG_SHTPS_SY3000_MULTI_1ST_DRSTEP	12
		#define CONFIG_SHTPS_SY3000_MULTI_2ND_DRSTEP	1
//		#define CONFIG_SHTPS_SY3000_FACETOUCH_DETECT
//		#define CONFIG_SHTPS_SY3000_FACETOUCH_OFF_DETECT
		#define CONFIG_SHTPS_SY3000_POSITION_OFFSET
//		#define CONFIG_SHTPS_SY3000_VIRTUAL_KEY
		#define CONFIG_SHTPS_SY3000_ALWAYS_ACTIVEMODE
//		#define CONFIG_SHTPS_SY3000_AUTOREZERO_CONTROL
//		#define CONFIG_SHTPS_SY3000_FLIP_CHANGE_HANDLE
	#endif

#elif defined(CONFIG_SHTPS_NASSAU_DEV)

	#undef CONFIG_SHTPS_NASSAU_PANEL_SIZE_X
	#undef CONFIG_SHTPS_NASSAU_PANEL_SIZE_Y
	#undef CONFIG_SHTPS_NASSAU_LCD_SIZE_X
	#undef CONFIG_SHTPS_NASSAU_LCD_SIZE_Y
	#undef CONFIG_SHTPS_NASSAU_SINGLE_ZERO_DRSTEP
	#undef CONFIG_SHTPS_NASSAU_SINGLE_1ST_DRSTEP
	#undef CONFIG_SHTPS_NASSAU_SINGLE_2ND_DRSTEP
	#undef CONFIG_SHTPS_NASSAU_MULTI_1ST_DRSTEP
	#undef CONFIG_SHTPS_NASSAU_MULTI_2ND_DRSTEP
	#undef CONFIG_SHTPS_NASSAU_PEN_SINGLE_ZERO_DRSTEP
	#undef CONFIG_SHTPS_NASSAU_PEN_SINGLE_1ST_DRSTEP
	#undef CONFIG_SHTPS_NASSAU_PEN_SINGLE_2ND_DRSTEP
	#undef CONFIG_SHTPS_NASSAU_PEN_MULTI_1ST_DRSTEP
	#undef CONFIG_SHTPS_NASSAU_PEN_MULTI_2ND_DRSTEP
	#undef CONFIG_SHTPS_NASSAU_POSITION_OFFSET
	#undef CONFIG_SHTPS_NASSAU_VIRTUAL_KEY
	#undef CONFIG_SHTPS_NASSAU_ALWAYS_ACTIVEMODE

	#if defined(CONFIG_SHTPS_NASSAU_TS2_001)
		#define CONFIG_SHTPS_NASSAU_PANEL_SIZE_X		799
		#define CONFIG_SHTPS_NASSAU_PANEL_SIZE_Y		1279
		#define CONFIG_SHTPS_NASSAU_LCD_SIZE_X			CONFIG_SHTPS_NASSAU_PANEL_SIZE_X
		#define CONFIG_SHTPS_NASSAU_LCD_SIZE_Y			CONFIG_SHTPS_NASSAU_PANEL_SIZE_Y
		#define CONFIG_SHTPS_NASSAU_SINGLE_ZERO_DRSTEP	4
		#define CONFIG_SHTPS_NASSAU_SINGLE_1ST_DRSTEP	4
		#define CONFIG_SHTPS_NASSAU_SINGLE_2ND_DRSTEP	1
		#define CONFIG_SHTPS_NASSAU_MULTI_1ST_DRSTEP	12
		#define CONFIG_SHTPS_NASSAU_MULTI_2ND_DRSTEP	1
		#define CONFIG_SHTPS_NASSAU_PEN_SINGLE_ZERO_DRSTEP	4
		#define CONFIG_SHTPS_NASSAU_PEN_SINGLE_1ST_DRSTEP	4
		#define CONFIG_SHTPS_NASSAU_PEN_SINGLE_2ND_DRSTEP	1
		#define CONFIG_SHTPS_NASSAU_PEN_MULTI_1ST_DRSTEP	4
		#define CONFIG_SHTPS_NASSAU_PEN_MULTI_2ND_DRSTEP	1
		#define CONFIG_SHTPS_NASSAU_POSITION_OFFSET
//		#define CONFIG_SHTPS_NASSAU_VIRTUAL_KEY
//		#define CONFIG_SHTPS_NASSAU_ALWAYS_ACTIVEMODE
	#endif

#endif

#endif /* __SHTPS_DEV_CFG_H__ */
