/* include/linux/input/sh_pmic8XXX-keypad.h
 *
 * Copyright (C) 2011 SHARP CORPORATION
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef __SH_PMIC8XXX_KEYPAD_H__
#define __SH_PMIC8XXX_KEYPAD_H__

#include <linux/input.h>
#include <../../../arch/arm/mach-msm/board-8960.h>

/*
 * NOTE: keymaps & param. of PMIC8XXX chip.
 */
#ifdef CONFIG_KEYBOARD_SCKEY

/* TENKEY key map */
#if (CONFIG_KEYPAD_TYPE == 0x2001)

#define KEY_ROW1_COL1	KEY_1
#define KEY_ROW1_COL2	KEY_4
#define KEY_ROW1_COL3	KEY_7
#define KEY_ROW1_COL4	KEY_STAR
#define KEY_ROW1_COL5	KEY_MENU
#define KEY_ROW1_COL6	KEY_RESERVED
#define KEY_ROW1_COL7	KEY_RESERVED
#define KEY_ROW1_COL8	KEY_RESERVED

#define KEY_ROW2_COL1	KEY_2
#define KEY_ROW2_COL2	KEY_5
#define KEY_ROW2_COL3	KEY_8
#define KEY_ROW2_COL4	KEY_0
#define KEY_ROW2_COL5	KEY_LSK
#define KEY_ROW2_COL6	KEY_RESERVED
#define KEY_ROW2_COL7	KEY_RESERVED
#define KEY_ROW2_COL8	KEY_RESERVED

#define KEY_ROW3_COL1	KEY_3
#define KEY_ROW3_COL2	KEY_6
#define KEY_ROW3_COL3	KEY_9
#define KEY_ROW3_COL4	KEY_POUND
#define KEY_ROW3_COL5	KEY_RSK
#define KEY_ROW3_COL6	KEY_RESERVED
#define KEY_ROW3_COL7	KEY_RESERVED
#define KEY_ROW3_COL8	KEY_RESERVED

#define KEY_ROW4_COL1	KEY_RESERVED
#define KEY_ROW4_COL2	KEY_BACK
#define KEY_ROW4_COL3	KEY_RESERVED
#define KEY_ROW4_COL4	KEY_RESERVED
#define KEY_ROW4_COL5	KEY_RESERVED
#define KEY_ROW4_COL6	KEY_UP
#define KEY_ROW4_COL7	KEY_LEFT
#define KEY_ROW4_COL8	KEY_RESERVED

#define KEY_ROW5_COL1	KEY_RESERVED
#define KEY_ROW5_COL2	KEY_VOLUMEDOWN
#define KEY_ROW5_COL3	KEY_VOLUMEUP
#define KEY_ROW5_COL4	KEY_RESERVED
#define KEY_ROW5_COL5	KEY_RESERVED
#define KEY_ROW5_COL6	KEY_RESERVED
#define KEY_ROW5_COL7	KEY_RESERVED
#define KEY_ROW5_COL8	KEY_RESERVED

#define KEY_ROW6_COL1	KEY_BACKSPACE
#define KEY_ROW6_COL2	KEY_SEND
#define KEY_ROW6_COL3	KEY_CAMERA
#define KEY_ROW6_COL4	KEY_FOCUS
#define KEY_ROW6_COL5	KEY_ENTER
#define KEY_ROW6_COL6	KEY_DOWN
#define KEY_ROW6_COL7	KEY_RIGHT
#define KEY_ROW6_COL8	KEY_RESERVED

#define KEY_ROW7_COL1	KEY_RESERVED
#define KEY_ROW7_COL2	KEY_RESERVED
#define KEY_ROW7_COL3	KEY_RESERVED
#define KEY_ROW7_COL4	KEY_RESERVED
#define KEY_ROW7_COL5	KEY_RESERVED
#define KEY_ROW7_COL6	KEY_RESERVED
#define KEY_ROW7_COL7	KEY_RESERVED
#define KEY_ROW7_COL8	KEY_RESERVED

#define KEY_ROW8_COL1	KEY_RESERVED
#define KEY_ROW8_COL2	KEY_RESERVED
#define KEY_ROW8_COL3	KEY_RESERVED
#define KEY_ROW8_COL4	KEY_RESERVED
#define KEY_ROW8_COL5	KEY_RESERVED
#define KEY_ROW8_COL6	KEY_RESERVED
#define KEY_ROW8_COL7	KEY_RESERVED
#define KEY_ROW8_COL8	KEY_RESERVED

#define KEY_ROW9_COL1	KEY_RESERVED
#define KEY_ROW9_COL2	KEY_RESERVED
#define KEY_ROW9_COL3	KEY_RESERVED
#define KEY_ROW9_COL4	KEY_RESERVED
#define KEY_ROW9_COL5	KEY_RESERVED
#define KEY_ROW9_COL6	KEY_RESERVED
#define KEY_ROW9_COL7	KEY_RESERVED
#define KEY_ROW9_COL8	KEY_RESERVED

#define KEY_ROW10_COL1	KEY_RESERVED
#define KEY_ROW10_COL2	KEY_RESERVED
#define KEY_ROW10_COL3	KEY_RESERVED
#define KEY_ROW10_COL4	KEY_RESERVED
#define KEY_ROW10_COL5	KEY_RESERVED
#define KEY_ROW10_COL6	KEY_RESERVED
#define KEY_ROW10_COL7	KEY_RESERVED
#define KEY_ROW10_COL8	KEY_RESERVED

#define KEY_ROW11_COL1	KEY_RESERVED
#define KEY_ROW11_COL2	KEY_RESERVED
#define KEY_ROW11_COL3	KEY_RESERVED
#define KEY_ROW11_COL4	KEY_RESERVED
#define KEY_ROW11_COL5	KEY_RESERVED
#define KEY_ROW11_COL6	KEY_RESERVED
#define KEY_ROW11_COL7	KEY_RESERVED
#define KEY_ROW11_COL8	KEY_RESERVED

#define KEY_ROW12_COL1	KEY_RESERVED
#define KEY_ROW12_COL2	KEY_RESERVED
#define KEY_ROW12_COL3	KEY_RESERVED
#define KEY_ROW12_COL4	KEY_RESERVED
#define KEY_ROW12_COL5	KEY_RESERVED
#define KEY_ROW12_COL6	KEY_RESERVED
#define KEY_ROW12_COL7	KEY_RESERVED
#define KEY_ROW12_COL8	KEY_RESERVED

/* PM8XXX chip param. */
#define SH_INPUT_NAME			"SH_tenkey-keypad"
#define SH_INPUT_PHYS_DEVICE	"SH_tenkey-keypad/input0"
#define SH_NUM_ROWS				6
#define SH_NUM_COLS				7
#define SH_ROWS_GPIO_START		PM8921_GPIO_PM_TO_SYS(9)
#define SH_COLS_GPIO_START		PM8921_GPIO_PM_TO_SYS(1)
#define SH_INIT_NUM_ROWS		6
#define SH_INIT_NUM_COLS		7
#define SH_DEBOUNCE_MS			15
#define SH_SCAN_DELAY_MS		32
#define SH_HOLD_NS				91500


/* MATRIX key map */
#elif (CONFIG_KEYPAD_TYPE == 0x1001)

#define	KEY_ROW1_COL1	KEY_RESERVED
#define	KEY_ROW1_COL2	KEY_RESERVED
#define	KEY_ROW1_COL3	KEY_RESERVED
#define	KEY_ROW1_COL4	KEY_RESERVED
#ifdef CONFIG_KEYBOARD_GEIGERKEY
#define	KEY_ROW1_COL5	KEY_RESERVED
#define	KEY_ROW1_COL6	KEY_RESERVED
#define	KEY_ROW1_COL7	KEY_APP1
#else
#define	KEY_ROW1_COL5	KEY_VOLUMEUP
#define	KEY_ROW1_COL6	KEY_VOLUMEDOWN
#define	KEY_ROW1_COL7	KEY_RESERVED
#endif
#define	KEY_ROW1_COL8	KEY_RESERVED

#define	KEY_ROW2_COL1	KEY_RESERVED
#define	KEY_ROW2_COL2	KEY_RESERVED
#define	KEY_ROW2_COL3	KEY_RESERVED
#define	KEY_ROW2_COL4	KEY_RESERVED
#define	KEY_ROW2_COL5	KEY_RESERVED
#define	KEY_ROW2_COL6	KEY_RESERVED
#define	KEY_ROW2_COL7	KEY_RESERVED
#define	KEY_ROW2_COL8	KEY_RESERVED

#define	KEY_ROW3_COL1	KEY_RESERVED
#define	KEY_ROW3_COL2	KEY_RESERVED
#define	KEY_ROW3_COL3	KEY_RESERVED
#define	KEY_ROW3_COL4	KEY_RESERVED
#define	KEY_ROW3_COL5	KEY_RESERVED
#define	KEY_ROW3_COL6	KEY_RESERVED
#define	KEY_ROW3_COL7	KEY_RESERVED
#define	KEY_ROW3_COL8	KEY_RESERVED

#define	KEY_ROW4_COL1	KEY_RESERVED
#define	KEY_ROW4_COL2	KEY_RESERVED
#define	KEY_ROW4_COL3	KEY_RESERVED
#define	KEY_ROW4_COL4	KEY_RESERVED
#define	KEY_ROW4_COL5	KEY_RESERVED
#define	KEY_ROW4_COL6	KEY_RESERVED
#define	KEY_ROW4_COL7	KEY_RESERVED
#define	KEY_ROW4_COL8	KEY_RESERVED

#define	KEY_ROW5_COL1	KEY_RESERVED
#define	KEY_ROW5_COL2	KEY_RESERVED
#define	KEY_ROW5_COL3	KEY_RESERVED
#define	KEY_ROW5_COL4	KEY_RESERVED
#define	KEY_ROW5_COL5	KEY_RESERVED
#define	KEY_ROW5_COL6	KEY_RESERVED
#define	KEY_ROW5_COL7	KEY_RESERVED
#define	KEY_ROW5_COL8	KEY_RESERVED

#define	KEY_ROW6_COL1	KEY_RESERVED
#define	KEY_ROW6_COL2	KEY_RESERVED
#define	KEY_ROW6_COL3	KEY_RESERVED
#define	KEY_ROW6_COL4	KEY_RESERVED
#define	KEY_ROW6_COL5	KEY_RESERVED
#define	KEY_ROW6_COL6	KEY_RESERVED
#define	KEY_ROW6_COL7	KEY_RESERVED
#define	KEY_ROW6_COL8	KEY_RESERVED

#define	KEY_ROW7_COL1	KEY_RESERVED
#define	KEY_ROW7_COL2	KEY_RESERVED
#define	KEY_ROW7_COL3	KEY_RESERVED
#define	KEY_ROW7_COL4	KEY_RESERVED
#define	KEY_ROW7_COL5	KEY_RESERVED
#define	KEY_ROW7_COL6	KEY_RESERVED
#define	KEY_ROW7_COL7	KEY_RESERVED
#define	KEY_ROW7_COL8	KEY_RESERVED

#define	KEY_ROW8_COL1	KEY_RESERVED
#define	KEY_ROW8_COL2	KEY_RESERVED
#define	KEY_ROW8_COL3	KEY_RESERVED
#define	KEY_ROW8_COL4	KEY_RESERVED
#define	KEY_ROW8_COL5	KEY_RESERVED
#define	KEY_ROW8_COL6	KEY_RESERVED
#define	KEY_ROW8_COL7	KEY_RESERVED
#define	KEY_ROW8_COL8	KEY_RESERVED

#define	KEY_ROW9_COL1	KEY_RESERVED
#define	KEY_ROW9_COL2	KEY_RESERVED
#define	KEY_ROW9_COL3	KEY_RESERVED
#define	KEY_ROW9_COL4	KEY_RESERVED
#define	KEY_ROW9_COL5	KEY_RESERVED
#define	KEY_ROW9_COL6	KEY_RESERVED
#define	KEY_ROW9_COL7	KEY_RESERVED
#define	KEY_ROW9_COL8	KEY_RESERVED

#define	KEY_ROW10_COL1	KEY_RESERVED
#define	KEY_ROW10_COL2	KEY_RESERVED
#define	KEY_ROW10_COL3	KEY_RESERVED
#define	KEY_ROW10_COL4	KEY_RESERVED
#define	KEY_ROW10_COL5	KEY_RESERVED
#define	KEY_ROW10_COL6	KEY_RESERVED
#define	KEY_ROW10_COL7	KEY_RESERVED
#define	KEY_ROW10_COL8	KEY_RESERVED

#define	KEY_ROW11_COL1	KEY_RESERVED
#define	KEY_ROW11_COL2	KEY_RESERVED
#define	KEY_ROW11_COL3	KEY_RESERVED
#define	KEY_ROW11_COL4	KEY_RESERVED
#define	KEY_ROW11_COL5	KEY_RESERVED
#define	KEY_ROW11_COL6	KEY_RESERVED
#define	KEY_ROW11_COL7	KEY_RESERVED
#define	KEY_ROW11_COL8	KEY_RESERVED

#define	KEY_ROW12_COL1	KEY_RESERVED
#define	KEY_ROW12_COL2	KEY_RESERVED
#define	KEY_ROW12_COL3	KEY_RESERVED
#define	KEY_ROW12_COL4	KEY_RESERVED
#define	KEY_ROW12_COL5	KEY_RESERVED
#define	KEY_ROW12_COL6	KEY_RESERVED
#define	KEY_ROW12_COL7	KEY_RESERVED
#define	KEY_ROW12_COL8	KEY_RESERVED

/* PM8XXX chip param. */
#define SH_INPUT_NAME			"SH_matrix-keypad"
#define SH_INPUT_PHYS_DEVICE	"SH_matrix-keypad/input0"
#define SH_NUM_ROWS				1
#define SH_NUM_COLS				8
#define SH_ROWS_GPIO_START		PM8921_GPIO_PM_TO_SYS(9)
#define SH_COLS_GPIO_START		PM8921_GPIO_PM_TO_SYS(1)
#define SH_INIT_NUM_ROWS		1
#define SH_INIT_NUM_COLS		8
#define SH_DEBOUNCE_MS			15
#define SH_SCAN_DELAY_MS		32
#define SH_HOLD_NS				91500
#ifdef CONFIG_KEYBOARD_GEIGERKEY
#define SH_WAKEUP				1
#else
#define SH_WAKEUP				0
#endif

#else

#define	KEY_ROW1_COL1	KEY_MENU
#define	KEY_ROW1_COL2	KEY_HOME
#define	KEY_ROW1_COL3	KEY_BACK
#define	KEY_ROW1_COL4	KEY_SEARCH
#define	KEY_ROW1_COL5	KEY_VOLUMEUP
#define	KEY_ROW1_COL6	KEY_VOLUMEDOWN
#define	KEY_ROW1_COL7	KEY_CAMERA
#define	KEY_ROW1_COL8	KEY_FOCUS

#define	KEY_ROW2_COL1	KEY_RESERVED
#define	KEY_ROW2_COL2	KEY_RESERVED
#define	KEY_ROW2_COL3	KEY_RESERVED
#define	KEY_ROW2_COL4	KEY_RESERVED
#define	KEY_ROW2_COL5	KEY_RESERVED
#define	KEY_ROW2_COL6	KEY_RESERVED
#define	KEY_ROW2_COL7	KEY_RESERVED
#define	KEY_ROW2_COL8	KEY_RESERVED

#define	KEY_ROW3_COL1	KEY_RESERVED
#define	KEY_ROW3_COL2	KEY_RESERVED
#define	KEY_ROW3_COL3	KEY_RESERVED
#define	KEY_ROW3_COL4	KEY_RESERVED
#define	KEY_ROW3_COL5	KEY_RESERVED
#define	KEY_ROW3_COL6	KEY_RESERVED
#define	KEY_ROW3_COL7	KEY_RESERVED
#define	KEY_ROW3_COL8	KEY_RESERVED

#define	KEY_ROW4_COL1	KEY_RESERVED
#define	KEY_ROW4_COL2	KEY_RESERVED
#define	KEY_ROW4_COL3	KEY_RESERVED
#define	KEY_ROW4_COL4	KEY_RESERVED
#define	KEY_ROW4_COL5	KEY_RESERVED
#define	KEY_ROW4_COL6	KEY_RESERVED
#define	KEY_ROW4_COL7	KEY_RESERVED
#define	KEY_ROW4_COL8	KEY_RESERVED

#define	KEY_ROW5_COL1	KEY_RESERVED
#define	KEY_ROW5_COL2	KEY_RESERVED
#define	KEY_ROW5_COL3	KEY_RESERVED
#define	KEY_ROW5_COL4	KEY_RESERVED
#define	KEY_ROW5_COL5	KEY_RESERVED
#define	KEY_ROW5_COL6	KEY_RESERVED
#define	KEY_ROW5_COL7	KEY_RESERVED
#define	KEY_ROW5_COL8	KEY_RESERVED

#define	KEY_ROW6_COL1	KEY_RESERVED
#define	KEY_ROW6_COL2	KEY_RESERVED
#define	KEY_ROW6_COL3	KEY_RESERVED
#define	KEY_ROW6_COL4	KEY_RESERVED
#define	KEY_ROW6_COL5	KEY_RESERVED
#define	KEY_ROW6_COL6	KEY_RESERVED
#define	KEY_ROW6_COL7	KEY_RESERVED
#define	KEY_ROW6_COL8	KEY_RESERVED

#define	KEY_ROW7_COL1	KEY_RESERVED
#define	KEY_ROW7_COL2	KEY_RESERVED
#define	KEY_ROW7_COL3	KEY_RESERVED
#define	KEY_ROW7_COL4	KEY_RESERVED
#define	KEY_ROW7_COL5	KEY_RESERVED
#define	KEY_ROW7_COL6	KEY_RESERVED
#define	KEY_ROW7_COL7	KEY_RESERVED
#define	KEY_ROW7_COL8	KEY_RESERVED

#define	KEY_ROW8_COL1	KEY_RESERVED
#define	KEY_ROW8_COL2	KEY_RESERVED
#define	KEY_ROW8_COL3	KEY_RESERVED
#define	KEY_ROW8_COL4	KEY_RESERVED
#define	KEY_ROW8_COL5	KEY_RESERVED
#define	KEY_ROW8_COL6	KEY_RESERVED
#define	KEY_ROW8_COL7	KEY_RESERVED
#define	KEY_ROW8_COL8	KEY_RESERVED

#define	KEY_ROW9_COL1	KEY_RESERVED
#define	KEY_ROW9_COL2	KEY_RESERVED
#define	KEY_ROW9_COL3	KEY_RESERVED
#define	KEY_ROW9_COL4	KEY_RESERVED
#define	KEY_ROW9_COL5	KEY_RESERVED
#define	KEY_ROW9_COL6	KEY_RESERVED
#define	KEY_ROW9_COL7	KEY_RESERVED
#define	KEY_ROW9_COL8	KEY_RESERVED

#define	KEY_ROW10_COL1	KEY_RESERVED
#define	KEY_ROW10_COL2	KEY_RESERVED
#define	KEY_ROW10_COL3	KEY_RESERVED
#define	KEY_ROW10_COL4	KEY_RESERVED
#define	KEY_ROW10_COL5	KEY_RESERVED
#define	KEY_ROW10_COL6	KEY_RESERVED
#define	KEY_ROW10_COL7	KEY_RESERVED
#define	KEY_ROW10_COL8	KEY_RESERVED

#define	KEY_ROW11_COL1	KEY_RESERVED
#define	KEY_ROW11_COL2	KEY_RESERVED
#define	KEY_ROW11_COL3	KEY_RESERVED
#define	KEY_ROW11_COL4	KEY_RESERVED
#define	KEY_ROW11_COL5	KEY_RESERVED
#define	KEY_ROW11_COL6	KEY_RESERVED
#define	KEY_ROW11_COL7	KEY_RESERVED
#define	KEY_ROW11_COL8	KEY_RESERVED

#define	KEY_ROW12_COL1	KEY_RESERVED
#define	KEY_ROW12_COL2	KEY_RESERVED
#define	KEY_ROW12_COL3	KEY_RESERVED
#define	KEY_ROW12_COL4	KEY_RESERVED
#define	KEY_ROW12_COL5	KEY_RESERVED
#define	KEY_ROW12_COL6	KEY_RESERVED
#define	KEY_ROW12_COL7	KEY_RESERVED
#define	KEY_ROW12_COL8	KEY_RESERVED

/* PM8XXX chip param. */
#define SH_INPUT_NAME			"SH_keypad"
#define SH_INPUT_PHYS_DEVICE	"SH_keypad/input0"
#define SH_NUM_ROWS				1
#define SH_NUM_COLS				8
#define SH_ROWS_GPIO_START		PM8921_GPIO_PM_TO_SYS(9)
#define SH_COLS_GPIO_START		PM8921_GPIO_PM_TO_SYS(1)
#define SH_INIT_NUM_ROWS		1
#define SH_INIT_NUM_COLS		8
#define SH_DEBOUNCE_MS			15
#define SH_SCAN_DELAY_MS		32
#define SH_HOLD_NS				91500

#endif	/* #if (CONFIG_KEYPAD_TYPE == 0x2000) */
#endif	/* CONFIG_KEYBOARD_SCKEY */

#endif	/* __SH_PMIC8XXX_KEYPAD_H__ */

